### ISSUE TITLE
Add en_US

### ISSUE THREAD

**Issue by fudom** [jenkinsci/locale-plugin#226]
Can we add `en_US`? I only see `en_GB`.

Btw. Is it possible to let the user decide this setting in its user settings? So the user can keep the browser language and only set a different language for Jenkins only.

**Comment by jonesbusy** [comment]
I think the solution is to change the "en_GB" to "en". 

"en" is the default locale for Jenkins

This will also requiring to bump to from "2.452.1" to "2.452.3" because of this fix on core: https://issues.jenkins.io/browse/JENKINS-73246

If not some help text might still use the browser language.

I will open a PR soon with this change

**Comment by jonesbusy** [comment]
Fixed by #233 by adding the 'en' language and fix of https://issues.jenkins.io/browse/JENKINS-73246
